Added JuMP.reduced_cost
pulsipher/InfiniteOpt.jl pull request #92
Opened 2020-11-30 19:11 UTC by bdaves12

Added JuMP.reduced_cost to variable queries. Returns the reduced cost for an infinite variable.
Addresses: #57

2020-11-30 21:39 UTC, pulsipher requested changes
This looks pretty good. It just needs a few final touches:
1. In `docs/make.jl` set `doctest = true`
2. Make a docstring for `map_reduced_cost` and include this in the documentation (note it will require `InfiniteOpt.map_reduced_cost` (this should mirror would is done for `map_value`)
3. Finish the example in the docstring for `JuMP.reduced_cost` by putting the expected result (just put a number there)
4. Remove the initial indent that has been added to line 1 in `src/results.jl`

2020-12-09 23:58 UTC, Madeintheshade commented
Is there any way to message yourself directly I might know of the slight minor touches that you're needing.

2021-01-12 18:58 UTC, pulsipher requested changes
Thanks for these changes, just 2 small things with regard to the docstring for `map_reduced_cost`. 
1. Its content should be modified to only refer to variable references (not expressions or constraints)
2. This docstring should be included in the documentation just like your `reduced_cost` function's docstring.

2021-02-02 23:11 UTC, pulsipher approved these changes

2021-02-03 16:16 UTC, merged